import { deserializationPolicy } from "@azure/ms-rest-js";

import { BrowserPolicyFactory } from "./BrowserPolicyFactory";
import { Credential } from "./credentials/Credential";
import { StorageClientContext } from "./generated/lib/storageClientContext";
import { LoggingPolicyFactory } from "./LoggingPolicyFactory";
import { IHttpClient, IHttpPipelineLogger, Pipeline } from "./Pipeline";
import { IRetryOptions, RetryPolicyFactory } from "./RetryPolicyFactory";
import {
  ITelemetryOptions,
  TelemetryPolicyFactory
} from "./TelemetryPolicyFactory";
import { UniqueRequestIDPolicyFactory } from "./UniqueRequestIDPolicyFactory";
import { escapeURLPath } from "./utils/utils.common";

export { deserializationPolicy };

/**
 * A ServiceURL represents a based URL class for ServiceURL, ContainerURL and etc.
 *
 * @export
 * @class StorageURL
 */
export abstract class StorageURL {
  /**
   * A static method used to create a new Pipeline (pipeline) object with Credential provided.
   *
   * @static
   * @param {Credential} credential credential Such as AnonymousCredential, SharedKeyCredential or TokenCredential.
   * @param {IHttpClient} [httpClient] the HttpClient that will be used to send HTTP requests.
   * @param {ITelemetryOptions} [telemetry] telemetry options
   * @param {IRetryOptions} [retryOptions] retry options
   * @param {IHttpPipelineLogger} [httpPipelineLogger] the HttpPipelineLogger that can be used to debug RequestPolicies within the HTTP pipeline.
   * @returns {Pipeline} a new Pipeline object
   * @memberof StorageURL
   */
  public static newPipeline(
    credential: Credential,
    httpClient?: IHttpClient,
    telemetry?: ITelemetryOptions,
    retryOptions?: IRetryOptions,
    httpPipelineLogger?: IHttpPipelineLogger): Pipeline {
    // Order is important. Closer to the API at the top & closer to the network at the bottom.
    // The credential's policy factory must appear close to the wire so it can sign any
    // changes made by other factories (like UniqueRequestIDPolicyFactory)
    const requestPolicyFactories = [
      new TelemetryPolicyFactory(telemetry),
      new UniqueRequestIDPolicyFactory(),
      new BrowserPolicyFactory(),
      deserializationPolicy(), // Default deserializationPolicy is provided by protocol layer
      new RetryPolicyFactory(retryOptions),
      new LoggingPolicyFactory(),
      credential
    ];

    return {
      httpClient,
      httpPipelineLogger,
      requestPolicyFactories,
    };
  }

  /**
   * Request policy pipeline.
   *
   * @internal
   * @type {Pipeline}
   * @memberof StorageURL
   */
  public readonly pipeline: Pipeline;

  /**
   * Encoded URL string value.
   *
   * @type {string}
   * @memberof StorageURL
   */
  public readonly url: string;

  /**
   * StorageClient is a reference to protocol layer operations entry, which is
   * generated by AutoRest generator.
   *
   * @protected
   * @type {StorageClient}
   * @memberof StorageURL
   */
  protected readonly storageClientContext: StorageClientContext;

  /**
   * Creates an instance of StorageURL.
   * @param {string} url
   * @param {Pipeline} pipeline
   * @memberof StorageURL
   */
  protected constructor(url: string, pipeline: Pipeline) {
    // URL should be encoded and only once, protocol layer shouldn't encode URL again
    this.url = escapeURLPath(url);
    this.pipeline = pipeline;
    this.storageClientContext = new StorageClientContext(
      this.url,
      {
        httpClient: pipeline.httpClient,
        httpPipelineLogger: pipeline.httpPipelineLogger,
        requestPolicyFactories: pipeline.requestPolicyFactories
      }
    );

    // Override protocol layer's default content-type
    const storageClientContext = this.storageClientContext as any;
    storageClientContext.requestContentType = undefined;
  }
}
